### ISSUE TITLE
Otat Frage zum Verständnis

### ISSUE THREAD

**Issue by SimonAlm** [medizinmedien/one-time-access-token#4]
@hostz-frank:

wenn ich eine otat kapagne anlege und versende und dann eine neue kampagne mit derselben seite, sollte die erste kampagne dadurch nicht ungültig werden, richtig?

Bitte um kurze Bestätigung, bevor ich aktuell so eine zweite Kampagne anlege mit neuen Usern.

**Comment by hostz-frank** [comment]
> sollte die erste kampagne dadurch nicht ungültig werden, richtig?

Richtig, gecheckt wird das Token - und wenn die zum Token zugehörige Kampagne die richtigen Parameter hat (Gültigkeit, Dauer, Seite etc.) dann wird das Cookie zum Zugriff gesetzt. Das ist von der Seite (die ja eben nur ein Kampagnen-Parameter ist) im Grunde unabhängig. Du kannst jede Menge Kampagnen auf eine einzelne Seite ansetzen, oder, anders gedeutet, z.B. auch mit einer weiteren Kampagne eine bestehende quasi erweitern.

**Comment by SimonAlm** [comment]
Danke!
