### ISSUE TITLE
emailadressen nicht in Datenbank geladen?

### ISSUE THREAD

**Issue by SimonAlm** [medizinmedien/one-time-access-token#5]
@hostz-frank 
ich habe beim letzten kampagnenversuch bemerkt, dass es einen Fehler gibt beim test- die seite wird zwar angezeigt, aber der brightcode wird nicht angezeigt.
Grund dafür dürfte sein, dass die emailadressen nicht in die Datenbank eingespielt wurden, OBWOHL ich das angeklickt hatte beim tokenizung prozess.

man erkennt das daran, dass bright angibt man solle sich einloggen

**Comment by SimonAlm** [comment]
![image](https://cloud.githubusercontent.com/assets/8351449/8458269/7c290b96-2016-11e5-9a0f-b7d2ee10cba2.png)

**Comment by SimonAlm** [comment]
hier zu sehen, bright kann den user nicht zuordnen und verlangt nach login or register.

die kampagne ist http://medonline.at/2015/dfp-invasiven-mykosen/ und es wären 2258 adressen betroffen, es ging auch viel zu schnell beim token export, früher brauchte es länger, wenn emailadresse in die datenbank geschoben wurden.
pls have a look

**Comment by hostz-frank** [comment]
Kannst du die Kampagne löschen und nochmals anlegen?  Und nochmals in die CSV-Datei schauen, ob die 1. Zeile wirklich Überschriften hat und die E-Mails in der 1. Spalte stehen - und zwar nei allen Zeilen ...
Bin nicht am PC und unterwegs ...

-------- Ursprüngliche Nachricht --------
Von: Simon Almassy <notifications@github.com> 
Datum: 01.07.2015  17:21  (GMT+01:00) 
An: medizinmedien/one-time-access-token <one-time-access-token@noreply.github.com> 
Cc: Frank <frank@hostz.at> 
Betreff: [one-time-access-token] emailadressen nicht in Datenbank geladen?
  (#5) 

@hostz-frank 

ich habe beim letzten kampagnenversuch bemerkt, dass es einen Fehler gibt beim test- die seite wird zwar angezeigt, aber der brightcode wird nicht angezeigt.

Grund dafür dürfte sein, dass die emailadressen nicht in die Datenbank eingespielt wurden, OBWOHL ich das angeklickt hatte beim tokenizung prozess.

man erkennt das daran, dass bright angibt man solle sich einloggen

**Comment by SimonAlm** [comment]
mach ich, eventuell auch ein neulogin bei medonline zuvor hilfreich..

**Comment by SimonAlm** [comment]
ok, noch immer dasselbe problem. aber bei einem test-gleiches kampagnenziel mit nur 2 adressen im csv ging es. eventuell ein problem in der csv datei mit den 2258 adressen?

kannst du eventuell bis morgen rausfinden wieso es dort nicht geht? cs

**Comment by hostz-frank** [comment]
Ja ich schau heute Abend hinein. Aber ich brauche eigtl. die CSV-Datei bzw. auch die Export-Vorlage ...

-------- Ursprüngliche Nachricht --------
Von: Simon Almassy <notifications@github.com> 
Datum: 01.07.2015  17:59  (GMT+01:00) 
An: medizinmedien/one-time-access-token <one-time-access-token@noreply.github.com> 
Cc: Frank <frank@hostz.at> 
Betreff: Re: [one-time-access-token] emailadressen nicht in Datenbank geladen?
  (#5) 

ok, noch immer dasselbe problem. aber bei einem test-gleiches kampagnenziel mit nur 2 adressen im csv ging es. eventuell ein problem in der csv datei mit den 2258 adressen?

kannst du eventuell bis morgen rausfinden wieso es dort nicht geht? cs

**Comment by SimonAlm** [comment]
per email gesendet

**Comment by SimonAlm** [comment]
wart, ich glaub beim zweiten mal hat's ohnehin funktioniert, da war vermutlich nur ein cache problem..

so hold on- ich teste nochmal- dürfte aber gehen

**Comment by SimonAlm** [comment]
Bitte doch mal checken, ob du die adressen in die db bekommst- von zuhause hatte ich das gleiche problem mit einem link, kein bright inhalt angezeigt obwohl eigentlich email hinterlegt sein sollte in DB:

https://medonline.at/2015/dfp-invasiven-mykosen/?otat=aaface736d4fae3cfe44d4c8f4ddd88e


Simon Almássy
Content Manager - Digital Services
Medizin Medien Austria GmbH
Grünbergstraße 15<x-apple-data-detectors://3/1> / Stiege 1, 1120 Wien
Tel. +43 1/ 54 600 - 652<tel:+43%201/%2054%20600%20-%20652>
E-Mail: almassy@medizin-medien.at<mailto:almassy@medizin-medien.at>



Beste Grüße
Simon Almassy


Am 01.07.2015 um 18:05 schrieb Frank <notifications@github.com<mailto:notifications@github.com>>:

Ja ich schau heute Abend hinein. Aber ich brauche eigtl. die CSV-Datei bzw. auch die Export-Vorlage ...

-------- Ursprüngliche Nachricht --------
Von: Simon Almassy <notifications@github.com<mailto:notifications@github.com>>
Datum: 01.07.2015 17:59 (GMT+01:00)
An: medizinmedien/one-time-access-token <one-time-access-token@noreply.github.com<mailto:one-time-access-token@noreply.github.com>>
Cc: Frank <frank@hostz.at<mailto:frank@hostz.at>>
Betreff: Re: [one-time-access-token] emailadressen nicht in Datenbank geladen? (#5)

ok, noch immer dasselbe problem. aber bei einem test-gleiches kampagnenziel mit nur 2 adressen im csv ging es. eventuell ein problem in der csv datei mit den 2258 adressen?

kannst du eventuell bis morgen rausfinden wieso es dort nicht geht? cs

—
Reply to this email directly or view it on GitHub.








—
Reply to this email directly or view it on GitHub<https://github.com/medizinmedien/one-time-access-token/issues/5#issuecomment-117728955>.


***
Medizin Medien Austria GmbH, Grünbergstrasse 15, 1120 Wien, UID ATU48742605, Handelsgericht Wien FN189189w, DVR-Nr. 4007613

**Comment by hostz-frank** [comment]
Das war haklig. Die csv-Datei war nicht im utf-8-Format abgespeichert, sondern als iso-9659-1 (westeuropäisch) - wodurch die Umlaute in einigen wenigen Mail-Adressen verstümmelt wurden. Da hat die Datenbank dann die Zus.arbeit verweigert. Irgend etwas war in Deinem Workflow anders als sonst, evtl.?! 

Ich habe jetzt aber eine Sicherheits-Konvertierung nach UTF-8 eingebaut, sodass das künftig egal sein sollte. Die Kampagne ist nun auch mit den Mail-Adressen gefüllt und der OTAT-Link oben funktioniert nun.

Wenn Du künftig solche Meldungen siehst:

`WordPress function "is_email()" returns FALSE for: susanne.gaube-schädler@wienkav.at, 
ursula.pöltner-gruber@wienkav.at, eva.plainer-zöchling@wienkav.at, elisabeth.edelenyi`

dann keine Panik: es bedeutet nicht, dass diese Mail-Adressen nicht so abgespeichert wurden, sondern lediglich, dass es zu Zustellproblemen kommen **könnte**. (`elisabeth.edelenyi` wird z.B. zweifellos zu einem Bounce führen und Umlaut-Mails können auch Probleme bei der Zustellung machen.) Das kann man aktuell nicht ändern.

Wenn Mails nach Import korrigierbar sein sollen, dann erfordert das Coding.

**Comment by SimonAlm** [comment]
Danke! Funktioniert
